stages:
  data_ingestion:
    cmd: python src/data_ingestion.py
    deps:
    - src/data_ingestion.py
    params:
    - data_ingestion.url
    outs:
    - data/row/Instruments_Reviews.csv
  data_preprocessing:
    cmd: python src/data_preprocessing.py
    deps:
    - data/row/Instruments_Reviews.csv
    - src/data_preprocessing.py
    outs:
    - data/processed_data/cleaned_reviews.csv
  feature_engineering:
    cmd: python src/feature_engineering.py
    deps:
    - data/processed_data/cleaned_reviews.csv
    - src/feature_engineering.py
    params:
    - feature_engineering.vectorizer_params
    outs:
    - artifacts/X_test.joblib
    - artifacts/X_train.joblib
    - artifacts/vectorizer.joblib
    - artifacts/y_test.joblib
    - artifacts/y_train.joblib
  model_building:
    cmd: python src/model_building.py
    deps:
    - artifacts/X_test.joblib
    - artifacts/X_train.joblib
    - artifacts/y_test.joblib
    - artifacts/y_train.joblib
    - src/model_building.py
    params:
    - model_building.model_params
    outs:
    - artifacts/sentiment_model.joblib
