data_ingestion:
  url: "https://raw.githubusercontent.com/RichardRivaldo/Sentiment-Analysis/refs/heads/main/Instruments_Reviews.csv"

feature_engineering:
  vectorizer_params:
    test_size: 0.3
    random_state: 40
    max_features: 20000
    ngram_range: [1, 2]
    min_df: 3

model_building:
  model_params:
    C: 2.0
    max_iter: 10000
    random_state: 40
    test_size: 0.2
    class_weight: "balanced"
